name: Trivy SBOM (CycloneDX)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  trivy-sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1) Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Go modules
        run: go mod download

      - name: Generate SBOM with Trivy (CycloneDX)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'cyclonedx'
          output: 'sbom-trivy-cyclonedx.json'

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-trivy-cyclonedx
          path: sbom-trivy-cyclonedx.json
